### ISSUE TITLE
Deriving instances requires ScopedTypeVariables

### ISSUE THREAD

**Issue by neongreen** [fpco/store#105]
This piece of code doesn't compile:

``` haskell
{-# LANGUAGE TemplateHaskell #-}

import TH.Derive
import Data.Store
import Data.Store.TH

data Foo a = Foo a

$($(derive [d|
    instance Store a => Deriving (Store (Foo a))
    |]))
```

```
Foo.hs:(9,3)-(11,7): error: …
    • Could not deduce (Store a1) arising from a use of ‘size’
      from the context: Store a
        bound by the instance declaration
        at Foo.hs:(9,3)-(11,7)
      Possible fix:
        add (Store a1) to the context of
          an expression type signature:
            Size a1
    • In the expression: (size :: Size a_a38ni)
```

It works fine with `ScopedTypeVariables` enabled.

Can TH derivation be fixed to work without `ScopedTypeVariables`? If not, I guess that there should be a warning in the documentation, and the code example should be amended to include `{-# LANGUAGE ScopedTypeVariables #-} -- required for 'derive' to work` or something.

**Comment by mgsloan** [comment]
Unfortunately scoped type variables are indeed required.  I actually added such a doc a couple days ago - https://github.com/fpco/store/commit/3d8a4a0d71f6c3d5f1e19a6aa84f2c9807fd8568#diff-6cd7c3ae59025c4fbb2e6b374772ee89R17

**Comment by mgsloan** [comment]
I've also updated the example - https://github.com/fpco/store/commit/d0b75fc516f0608217f2dbc7f38f01f03636aa66
