### ISSUE TITLE
store & store-core are not in stack nightly resolver

### ISSUE THREAD

**Issue by jchia** [fpco/store#117]
Putting `store-0.4.3.1` & `store-core-0.4.1` in `extra-deps` results in this error under `stack build` on a project with `nightly-2017-08-25`:
```
    /tmp/stack29424/store-0.4.3.1/src/Data/Store/Internal.hs:110:1: error:
        Could not find module ‘Data.Typeable.Internal’
        it is a hidden module in the package ‘base-4.10.0.0’
        Use -v to see a list of the files searched for.
        |
    110 | import           Data.Typeable.Internal (Typeable)
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Putting a github `packages->location` entry for `store` & `store-core` with the latest commit instead results in a successful build. So, perhaps the hackage is not the latest, either.

This affects people trying to use `stack` with GHC 8.2 & `store` for their projects.

**Comment by 4e6** [comment]
It is disabled in the current [Stackage plan](https://github.com/fpco/stackage/blob/b0979af7bd2717e52acd251960f1a612cc955f20/build-constraints.yaml#L280) due to a compilation failure. However, I haven't checked if it's still true.

```
# - stackage-curator # via store compilation failure
- store < 0 # compilation failure
```

**Comment by mgsloan** [comment]
I'm not sure I want to release the current changes, so I created a branch with a few fixes, in particular the compilation fix: https://github.com/fpco/store/tree/version-0.4.3.2

Pinging @snoyberg

**Comment by mgsloan** [comment]
(Also released that branch) Will close this once it's in stackage

**Comment by lwm** [comment]
Stackage PR https://github.com/fpco/store/issues/117 is merged 👍
