### ISSUE TITLE
Some sum types should have a ConstSize size

### ISSUE THREAD

**Issue by sjakobi** [fpco/store#119]
```
> f s = case s of { VarSize _ -> "VarSize"; ConstSize _ -> "ConstSize"}
> f (Data.Store.size :: Size (Either Int Word))
"VarSize"
```

IMO this should be a `ConstSize 9` as both `Int` and `Word` are `ConstSize 8` (on my 64-bit machine).

**Comment by mgsloan** [comment]
Good point! Fixed in https://github.com/fpco/store/commit/6b22382564939fb2110564d854a049527cd8199b
