### ISSUE TITLE
Test compilation failure

### ISSUE THREAD

**Issue by bergmark** [fpco/store#125]
When building stackage nightly:
```
test/Data/StoreSpec.hs:90:3: error:
    Duplicate instance declarations:
      instance Monad m => Serial m Word
        -- Defined at test/Data/StoreSpec.hs:90:3
      instance [overlap ok] Monad m => Serial m Word
        -- Defined in ‘Test.SmallCheck.Series’
   |
90 | $(do let ns = [ ''CWchar, ''CUShort, ''CULong, ''CULLong, ''CIntMax
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

The tests were already disabled in nightly for other (resolved) reasons, but I'll keep it disabled for now.

**Comment by mgsloan** [comment]
Fixed on master!

**Comment by bergmark** [comment]
Seems like the 0.5.0 release didn't resolve this.

**Comment by juhp** [comment]
Is this is 0.5.0.1?

**Comment by mgsloan** [comment]
Yup, at least 0.5.0.1 fixes the failures encountered when building against recent stackage nightly.  Sorry for taking so long to resolve this!
