### ISSUE TITLE
Gain more clarity on when store outperforms cereal and why

### ISSUE THREAD

**Issue by kantp** [fpco/store#20]
We currently have benchmarks where `store` is much faster than cereal (5-10x), mostly for large payloads, and smaller benchmarks where performance is equivalent.

It would be good to understand what is going on -- one possibility is that fixed costs in starting to serialize/deserialize dominate the short benchmarks. Another would be that some cache/memory behavior kicks in only when the data is large enough.

**Comment by mgsloan** [comment]
I think that due to chris's work with `weigh`, I think we can conclude that one of the big differences is how much fewer allocations `store` performs.  As such, closing the issue.
