### ISSUE TITLE
Optimize peekSequence

### ISSUE THREAD

**Issue by mgsloan** [fpco/store#28]
https://github.com/fpco/store/pull/26 suggests something similar might be beneficial for `peekSequence`.  However this is a little tricky as right now we are relying on https://hackage.haskell.org/package/mono-traversable-0.10.2/docs/Data-Sequences.html#v:replicateM .  We need something like `replicateM` but that does folding.  Could use StateT, but will it optimize better?

Also, implement `peekMap` and `peekSet` in terms of it.

**Comment by chrisdone** [comment]
Looking into it further I found that your INLINE commit actually removed the need for the manual inlining. It's probably not necessary now. Worth taking a look at again.

**Comment by mgsloan** [comment]
Woohoo, that's great news!
