### ISSUE TITLE
Possible multiple exceptions for the same decoding error

### ISSUE THREAD

**Issue by ygale** [fpco/store#32]
In `Data.Store.Impl`:

    decode = unsafePerformIO . try . decodeIO
    {-# INLINE decode #-}

The reason this is done in `IO` is so that `throwIO` can be used when a decoding error occurs.

This INLINE is unsafe. If GHC actually does inline this code in multiple places, you could generate the same decode error multiple times. It should be changed to NOINLINE.

A cleaner way to structure this would be to run the entire calculation in `Either` and then throw any asynchronous exception in one place at the top level.

**Comment by snoyberg** [comment]
There appear to be a lot of assumptions in this comment which aren't necessarily true. For example, talk of asynchronous exceptions seems out of place, and implying that the `IO` usage here is all about exceptions (it's because we're performing buffer reads).

I'm having trouble picturing what you're saying about the same decode error occurring multiple times, perhaps you could include a demonstration of the problem?

**Comment by mgsloan** [comment]
We also need `IO` for allocating mutable buffers and then writing to them (and later freezing them).

**Comment by ygale** [comment]
OK, I didn't see the buffer allocations. But that also might be a reason to avoid inlining `unsafePerformIO`. Are you sure you want that to happen an arbitrary number of times, at the whim of various unrelated algorithms within whatever version of GHC you happen to be using?

Besides the buffer allocations, the IO action that is happening within `decode` is `throwIO`. If GHC inlines this "pure" code in multiple places and runs it several times, could not that cause the exception to be thrown multiple times?

I called `unsafePerformIO . throwIO` an asynchronous exception. Because it is an exception, and it is thrown in pure code so it is asynchronous. But if you disagree with my use of that term here, feel free to consider it withdrawn.

**Comment by snoyberg** [comment]
> I called unsafePerformIO . throwIO an asynchronous exception. Because it is an exception, and it is thrown in pure code so it is asynchronous. But if you disagree with my use of that term here, feel free to consider it withdrawn.

I've usually heard that called an impure exception. But it's not relevant here, given that the code in question (that you quoted above) is:

    decode = unsafePerformIO . try . decodeIO

Note that the `try` will catch those exceptions, and therefore they will not be thrown from pure code.

I also don't see the argument about the inlining causing trouble. If we were discussing a value that itself has an exception in it, this argument would make sense. But we're not: we're discussing a function which, when applied to an input, may generate an exception. If _that_ call is inlined, the argument could make sense (barring my point above about us already catching these exceptions).

**Comment by mgsloan** [comment]
Closing, as no demonstration of a problem has been given.

> If GHC inlines this "pure" code in multiple places and runs it several times, could not that cause the exception to be thrown multiple times?

It is quite valid to inline `decode`.  Once inlined, GHC has no reason to duplicate the call.  Infact, this decode can have more sharing than `decodeIO`.  GHC is allowed to share duplicate `decode` invocations but not `decodeIO` invocations.  This could occur in reasonable practice if two functions involving decoding the same data get inlined together.

See this informative blogpost: http://mainisusuallyafunction.blogspot.com/2011/10/thunks-and-lazy-blackholes-introduction.html

It is true that the docs for `unsafePerformIO` say

> Use {-# NOINLINE foo #-} as a pragma on any function foo that calls unsafePerformIO. If the call is inlined, the I/O may be performed more than once.

I believe this could indeed occur in the case where you have

```
x = decode "...."

g = ... x ...

h = ... fx...
```

This is a rare and strange case.  If GHC decides to INLINE, well, nothing bad will happen, just a perf difference.

**Comment by ygale** [comment]
Summary:

This code violates the guidelines in the GHC documentation for use of `unsafePerformIO`.

My original claim of a specific problem that this will cause (the same error to be thrown multiple times) is wrong. More generally, you have checked carefully that this code will not cause problems. And presumably you have a good reason for using this non-recommended idiom - for example, you may have determined that using `unsafePerformIO` and `INLINE` for this particular function gives you a measurable performance boost.

Another similar issue is the ubiquitous use of `INLINE` rather than `INLINABLE`. It is recommended by the GHC team to use `INLINABLE` in most cases, but given this discussion I'll assume that for this too you have studied the two alternatives carefully and chosen the non-recommended one for a good reason. If not and you want me to open a separate ticket for it, please let me know.

**Comment by mgsloan** [comment]
I didn't benchmark `INLINE` vs `INLINABLE`, I think we need more comprehensive benchmarks in order to make that choice.
