### ISSUE TITLE
Move Data.Store.Impl to store-core?

### ISSUE THREAD

**Issue by TerrorJack** [fpco/store#62]
For package writers who prefer to hand-write their own `Store` instances, importing the `store` package is an overkill. A lot of extra dependencies aren't needed in this case.

**Comment by mgsloan** [comment]
This would mean that `store-core` would define the typeclass, and `store` would define the instances.  I'd rather avoid that degree of orphans.  The overall deps of `store` likely will be reduced, but it will define the typeclass / instances.
