### ISSUE TITLE
store-0.1.* misses upper bound on th-utilities, please consider editing bounds on Hackage

### ISSUE THREAD

**Issue by Blaisorblade** [fpco/store#65]
This allows cabal-based CI builds of stack to fail on CI (when not masked by caching as in commercialhaskell/stack#2428).

Because of the API change in th-utilities@1e23895fe90cd28dd1f232bc0ba4137dcdacfb6e, store-0.1.0.1 with th-utilities >= 0.2 doesn't compile. Instances on https://travis-ci.org/Blaisorblade/stack/jobs/149203734 and https://travis-ci.org/Blaisorblade/stack/jobs/149203736.

Relevant messages in the first case:

[Downloading th-utilities-0.2.0.1...](https://travis-ci.org/Blaisorblade/stack/jobs/149203734#L725)

[Configuring store-0.1.0.1...
Building store-0.1.0.1...
Preprocessing library store-0.1.0.1...
src/Data/Store/TH/Internal.hs:47:18:
    Could not find module ‘TH.ReifyDataType’
    Use -v to see a list of the files searched for.](https://travis-ci.org/Blaisorblade/stack/jobs/149203734#L960-L966).

**Comment by mgsloan** [comment]
Good point, done!
