### ISSUE TITLE
Adopt compact normal forms from GHC HEAD?

### ISSUE THREAD

**Issue by robstewart57** [fpco/store#68]
Preliminary support for compact regions was added to GHC on the 15 July. It is based on the approach presented in "Efficient Communication and Collection with Compact Normal Forms", Edward Z. Yang et.al. from ICFP 2015. The top level API is in Data.Compact: https://github.com/ghc/ghc/blob/cf989ffe490c146be4ed0fd7e0c00d3ff8fe1453/libraries/compact/Data/Compact.hs

Might this store library adopt compact normal forms support at some point?

**Comment by mgsloan** [comment]
That would be a really cool enhancement!  Certainly worth consideration once it is in a released GHC version!

**Comment by robstewart57** [comment]
This is the currently proposed API for the compact NF library, hopefully to coincide with GHC 8.2:

http://ezyang.com/compact/

**Comment by Blaisorblade** [comment]
Link became http://ezyang.com/compact.html now. The GHC 8.2 API is a bit different, see https://downloads.haskell.org/~ghc/master/libraries/html/compact/index.html.

**Comment by mgsloan** [comment]
I've looked into compact normal forms a bit, cool stuff! One issue with it is that they only work for serialization between identical executables, so not really the usecase store is intended for.
