### ISSUE TITLE
Bounds checks are vulnerable to overflow.

### ISSUE THREAD

**Issue by kantp** [fpco/store#70]
The bounds checks in the `peek` function are performed like this: `﻿⁠⁠⁠⁠plusPtr startPtr len > endPtr`.
This is vulnerable to overflow if `len` is large (which is likely to happen, for instance, when we read corrupt data).
We should change this to `minusPtr endPtr startPtr < len`.

**Comment by bitonic** [comment]
Merging the codefix since this is quite urgent, but please add a short comment in the cases where you do the check, e.g.

```
-- Do not perform the check on the new pointer, since it could have overflowed
```

**Comment by kantp** [comment]
I've added the comments.
