### ISSUE TITLE
Add unboxed vector instances

### ISSUE THREAD

**Issue by nh2** [fpco/store#90]
I suggest, analogous to the Vector instance:

```haskell
import qualified Data.Vector.Unboxed as VU
import qualified Data.Vector.Unboxed.Mutable as VUM

instance (VU.Unbox a, Store a) => Store (VU.Vector a) where
    size = sizeSequence
    poke = pokeSequence
    peek = VU.unsafeFreeze =<< peekMutableSequence VUM.new VUM.write
    {-# INLINE size #-}
    {-# INLINE peek #-}
    {-# INLINE poke #-}
```

**Comment by mgsloan** [comment]
We do actually generate all of the different instances for unboxed vectors - https://github.com/fpco/store/blob/4f65518c2a136f513d6fa07dfb65b45d7df11d81/src/Data/Store/TH/Internal.hs#L319

It's written this way for efficiency, so that we can use memcpy.  That said, it seems like the instances module takes quite a lot of memory to compile - https://github.com/fpco/store/issues/91 .  Might be worthwhile to go for a simpler implementation with less compilation.

**Comment by nh2** [comment]
@mgsloan Your answer made sense to me, and I can see these instances in the haddocks of [`Data.Store.Internal`](https://hackage.haskell.org/package/store-0.7.10/docs/Data-Store-Internal.html#v:-36-fStoreVector7):

![image](https://user-images.githubusercontent.com/399535/112738518-d6033200-8f63-11eb-86cb-aaa36bb4a61a.png)

(Have to hover them to see that the `Vector` is an `Unboxed` one here.)

---

A few years later, another question comes up though:

How does one do `Store` instances of Unboxed vectors of one's own data types?

For example, I have this neat data type with some "phantom" parameters:

```haskell
data EstimatedPose from to = EstimatedPose
  { epRotation :: M from to
  , epTranslation :: V to
  , epTriangulatedPoints :: VU.Vector (V from)
  , epInlierIndices :: VU.Vector Int
  } deriving (Eq, Show, Generic)
```

Trying to make an derived

```haskell
instance Store.Store (EstimatedPose from to)`
```

I'm confronted with:

```
No instance for (Store.Store (VU.Vector (V from)))
```

What's the correct way to provide such instances?

**Comment by nh2** [comment]
Or perhaps for a simpler example:

`data MyVector = MyVector (VU.Vector V4)`

where [`V4` is from `linear`](https://hackage.haskell.org/package/linear-1.21.5/docs/Linear-V4.html) and has `Unbox` and `Storable` instances.

**Comment by nh2** [comment]
My current workaround: Roundtripping via `Storable` (for which e.g. `V3` also has instances):

```haskell
import qualified Data.Vector.Generic as VG
import qualified Data.Vector.Storable as VS
import qualified Data.Vector.Unboxed as VU

data MyVector = MyVector (VU.Vector V3)

instance MyVector => Store.Store MyVector where
  size = contramap VG.convert Store.size
  peek = MyVector . VG.convert <$> Store.peek
  poke (MyVector vu) = Store.poke (VG.convert vu :: VS.Vector V3)
```

**Comment by mgsloan** [comment]
Hmm, I don't know of a straightforward way to do this with current store functionality.

The main approach that comes to mind is to create a function similar to [the function for deriving instances for unboxed vectors]( https://github.com/mgsloan/store/blob/24f0ab34ba2ea2887d099f5a6e1270792220e394/src/Data/Store/TH/Internal.hs#L335), which takes a list of types to derive `(Store (VU.Vector ...))`.  It would then find the matching data family instance, and derive store for the constructor on the rhs.
